spring:
  datasource:
    username: root
    password: Decypher#0
    url: jdbc:mysql://localhost:3306/hdb_tool
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect