spring:
  datasource:
    username: root
    password: Mysql@123
    url: jdbc:mysql://localhost:3306/hdd_tool
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect